import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "./textEditorStyles.css"
// import Navbar from "@/components/custom/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { Candal } from "next/font/google";
import AuthProvider from "../Provider/AuthProvider/AuthProvider";
import ReactQueryClientProvider from "../Provider/ReactQueryClientProvider";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider";
import Footer from "@/components/custom/Footer/Footer";
import { DataProvider } from "../Provider/DataProvider/DataProvider";
import Navbar from "@/components/custom/Navbar/Navbar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const candal = Candal({
  weight: "400", // only one weight available
  subsets: ["latin"],
  display: "swap",
  variable: "--font-candal", // optional but useful for Tailwind
});

export const metadata: Metadata = {
  title: "Korybay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>

      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={false}
          disableTransitionOnChange
        >

          <ReactQueryClientProvider>
            <DataProvider>
              <AuthProvider>

                <main>
                  <Navbar />
                  {children}
                  <Footer />
                </main>
                <Toaster />

              </AuthProvider>
            </DataProvider>
          </ReactQueryClientProvider>

        </ThemeProvider>

      </body>

    </html>
  );
}
